version: "3.9"

services:
  # Postgres database.
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yeeraf
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kontrol
    ports:
      - 5432:5432 # machine_port:container_port
